export const COLLECT_USER_AUTH_DATA = 'AUTH/COLLECT_USER_AUTH_DATA';
export const REFRESH_TOKEN = 'AUTH/REFRESH_TOKEN';
export const LOGOUT = 'AUTH/LOGOUT';
export const GET_POSTS = 'POSTS/GET_POSTS';
export const STORE_POSTS = 'POSTS/STORE_POSTS';
export const CHANGE_PAGE = 'POSTS/CHANGE_PAGE';
